version: "2.14.2"
name: polyas-verifier
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DIR: /srv/app
        NAME: polyas-verifier
      network: host
    container_name: polyas-verifier
    entrypoint:
    - /usr/local/bin/npm
    - run
    - start
    environment:
      VITE_ELECTION_URL: https://election.polyas.com
      VITE_ELECTION_HASH: a1d0c6e8-3f02-7327-d846-1063f4Ac58a6
      VITE_ELECTION_FINGERPRINT: 42
      RECEIPT_CAPACITY: 20KB
    extra_hosts:
      127.0.0.1: host-gateway
    image: node:alpine
    network_mode: bridge
    ports:
    - mode: host
      target: 5000
      host_ip: 127.0.0.1
      published: "5000"
      protocol: tcp
    restart: always
    tty: true
    working_dir: /srv/app/polyas-verifier
networks:
  default:
    driver: bridge
    external: true
